secretKey: 123456

pgSQL:
    host: localhost
    port: 15432
    user: postgres
    password: 998627
    dbName: blog-data
    sslMode: "disable"
    maxIdle: 10
    maxOpen: 100
    logLevel: "info"

middlewaresKeys:
    response:
        response: "response"
        statusCode: "statusCode"
        message: "message"
    validate:
        validated: "validated"
    auth:
        tokenKey: "Authorization"

minio:
    endpoint: "127.0.0.1"
    accessKeyID: "root"
    secretAccessKey: "12345678"
    useSSL: false
    bucket: "default"
